authors:
  zufar:
    name: Zufar Dhiyaulhaq
    description: Senior Engineering Manager @ GoTo Financial
    avatar: https://avatars.githubusercontent.com/u/11990726
    url: https://zufardhiyaulhaq.com
